### ISSUE TITLE
Make develop branch the default branch, like other NCEPLIBS projects

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-prod_util#31]
It would have been good if everyone just used the master branch as intended, but instead we are using develop - everywhere but here. Which leads to predicatble mistakes. ;-)

So let us make a develop branch and make it the default branch, just like everywhere else.

If we can ever switch all projects to use master branch instead of develop branch, I would be in favor of that. But to have all of them use develop while prod_util uses master is just to invite trouble.

**Comment by edwardhartnett** [comment]
Let's do this right after the upcoming 1.2.2 release.

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA I am going to do this right now. Let me know if this is a problem...

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA develop and master branch are different. Which one have you been releasing from?

**Comment by Hang-Lei-NOAA** [comment]
Hi, Edward
That should be done. I checked it before I make the 1.2.2. The develop is
the one used for recent releases.
The prod_util is used to be maintained by NCO. We just take it for 3 years.

**Comment by edwardhartnett** [comment]
OK, so I will make master the same as develop. Then I will make develop the default.

**Comment by edwardhartnett** [comment]
OK I have done this. I will close this issue.
