### ISSUE TITLE
Do a version 1.2.2 release

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-prod_util#35]
In support of hpc-stack-1.1.0 release, we need a release of prod_util which addresses the problem raised by @WenMeng-NOAA  in this issue: https://github.com/NOAA-EMC/hpc-stack/issues/73

**Comment by Hang-Lei-NOAA** [comment]
I will work on this with Wen.

**Comment by WenMeng-NOAA** [comment]
I tested the pro_util/1.2.1 with the fix. Now it looks good to me. Please implemented on other platforms. Thanks!

**Comment by Hang-Lei-NOAA** [comment]
okay
