### ISSUE TITLE
Enumerate the utilities provided in prod_util in the documentation

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-prod_util#40]
Specifically, what utilities are provided by prod_util?

I see fsync_file. Is that one of the utilities? Where are the others? In the ush directory?

@Hang-Lei-NOAA do you know?

**Comment by Hang-Lei-NOAA** [comment]
I don't know much about it. When I was the code manager for
global_workflow. We used some of the utilities. e.g. some under the
ush.like setpdy.sh is used to set up the time for workflow. nhour,
ndate etc exe utility is also for check system time.
